from .user import UserViewset
from .v_roles import RolesViewSet
from .empresa import EmpresaViewset
from .v_categorias import CategoriaViewSet
from .v_tickets import TicketsViewSet
from .v_proyectos import ProyectoViewset
from .v_fusion import FusionViewset
from .v_reporteria import ReporteriaViewSet
from .v_dashboard import DashboardViewSet
from .v_puestos import PuestosViewSet