# Generated by Django 2.2.13 on 2020-10-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
