# Generated by Django 2.2.13 on 2020-11-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tickets_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='fechaInicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
