# Generated by Django 2.2.13 on 2020-11-11 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201111_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='horasTrabajadas',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='HH:MM:SS'),
        ),
    ]
