# Generated by Django 2.2.13 on 2020-11-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201111_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='horasTrabajadas',
            field=models.TimeField(blank=True, max_length=25, null=True),
        ),
    ]
