# Generated by Django 2.2.13 on 2020-11-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201111_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='horasTrabajadas',
            field=models.DurationField(blank=True, null=True, verbose_name='HH:MM:SS'),
        ),
    ]
