# Generated by Django 2.2.13 on 2020-11-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_profile_scrum_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='scrum_master',
        ),
    ]
