# Generated by Django 2.2.13 on 2020-11-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_scrum_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puestos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('creadoPor', models.IntegerField(blank=True, null=True)),
                ('actualizadoPor', models.IntegerField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
