# Generated by Django 2.2.13 on 2020-11-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_puestos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='horasTrabajadas',
            field=models.TimeField(blank=True, max_length=25, null=True),
        ),
    ]
